---
fixtures:
  #repositories:
    #stdlib:
    #repo: "https://github.com/simp/puppetlabs-stdlib"
    #branch: "simp-master"
  symlinks:
    compliance_markup: "#{source_dir}"
    stdlib: "#{source_dir}/../stdlib"
