---
puppet-syntax: 
  stage: test
  tags: 
    - docker
  image: ruby:2.1
  script: 
    - bundle install
    - bundle exec rake syntax
puppet-lint: 
  stage: test
  tags: 
    - docker
  image: ruby:2.1
  script: 
    - bundle install
    - bundle exec rake lint
puppet-metadata: 
  stage: test
  tags: 
    - docker
  image: ruby:2.1
  script: 
    - bundle install
    - bundle exec rake metadata
unit-test-ruby-2.1:
  stage: test
  tags: 
    - docker
  image: ruby:2.1
  script: 
    - bundle install
    - bundle exec rake spec
unit-test-ruby-2.2:
  stage: test
  tags: 
    - docker
  image: ruby:2.2
  allow_failure: true
  script: 
    - bundle install
    - bundle exec rake spec
unit-test-ruby-2.3:
  stage: test
  tags: 
    - docker
  image: ruby:2.3
  allow_failure: true
  script: 
    - bundle install
    - bundle exec rake spec

# For PE LTS Support
# See: https://puppet.com/misc/puppet-enterprise-lifecycle
puppet4.7-syntax: 
  stage: test
  tags: 
    - docker
  image: ruby:2.1
  script: 
    - PUPPET_VERSION=4.7 bundle install
    - PUPPET_VERSION=4.7 bundle exec rake syntax
unit-test-puppet4.7-ruby-2.1:
  stage: test
  tags: 
    - docker
  image: ruby:2.1
  script: 
    - PUPPET_VERSION=4.7 bundle install
    - PUPPET_VERSION=4.7 bundle exec rake spec
unit-test-puppet4.7-ruby-2.2:
  stage: test
  tags: 
    - docker
  image: ruby:2.2
  allow_failure: true
  script: 
    - PUPPET_VERSION=4.7 bundle install
    - PUPPET_VERSION=4.7 bundle exec rake spec
unit-test-puppet4.7-ruby-2.3:
  stage: test
  tags: 
    - docker
  image: ruby:2.3
  allow_failure: true
  script: 
    - PUPPET_VERSION=4.7.0 bundle install
    - PUPPET_VERSION=4.7.0 bundle exec rake spec

acceptance-test-4.7: 
  stage: test
  tags: 
    - beaker
  script: 
    - bundle install --no-binstubs --path=vendor
    - PUPPET_VERSION=4.7.0 bundle update
    - PUPPET_VERSION=4.7.0 bundle exec rake acceptance
acceptance-test-4.8: 
  stage: test
  tags: 
    - beaker
  script: 
    - bundle install --no-binstubs --path=vendor
    - PUPPET_VERSION=4.8.0 bundle update
    - PUPPET_VERSION=4.8.0 bundle exec rake acceptance
acceptance-test-4.10.0: 
  stage: test
  tags: 
    - beaker
  script: 
    - bundle install --no-binstubs --path=vendor
    - PUPPET_VERSION=4.10.0 bundle update
    - PUPPET_VERSION=4.10.0 bundle exec rake acceptance
